### ISSUE TITLE
chromeext: Ensure descriptions good on chrome extension store front

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity-ui#1]
- Title: Parity Ethereum Integration
- ~~Short: Integrate the Parity Ethereum client with the Chrome browser~~
- ~~Long:
  Parity is an Ethereum client by leading Ethereum startup, Ethcore. This extension allows you to integrate important Parity functionality right into your Chrome browser experience. The extension provides integration with Parity URLs, allowing you to get to Dapps using simple naming like "wallet.dapp". The extension also allows you to inspect, confirm or ignore any transaction that Parity is requested to sign.
  To get the most out of this extension, ensure you have downloaded and installed the Parity Ethereum client, available at the Parity website, http://parity.io/.~~

**Comment by goldylucks** [comment]
@gavofyork plz check
https://chrome.google.com/webstore/detail/parity-ethereum-integrati/fgodinogimdopkigkcoelpfkbnpngalc
