### ISSUE TITLE
Error "Request with disallowed Host header has been blocked."

### ISSUE THREAD

**Issue by igorbarinov** [paritytech/parity-ui#106]
Hi guys,

i have parity client inside a docker container with dapps enabled `parity --dapps-port 8002 --dapps-interface 0.0.0.0 --dapps-user user --dapps-pass $DAPP_PASSWOR`. I mapped 8002 port to ouside of the containter `docker run -p 8002:8002`. After I start the container I get `Request with disallowed Host header has been blocked. Check the URL in your browser address bar.` when I'm trying to access 8002 port on a local machine by localhost or ip

Thank you in advance

**Comment by tomusdrw** [comment]
You need to listen on one specific interface and access the dapps server using this interface's IP address. 

There is also https://github.com/ethcore/parity/pull/2005 pending that will allow you to whitelist hosts allowed to access. If you are ok with building from sources try this branch.

**Comment by igorbarinov** [comment]
Thank you @tomusdrw 
I've solved it with providing eth0 address of container to dapps-interface `--dapps-interface $(ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1)` and using `-p 8001` in docker run string
and connecting to UI from host machine by using container ip address.

**Comment by igorbarinov** [comment]
I built with your patch and now I have "Used HTTP Method is not allowed. POST or OPTIONS is required" after basic auth.
The error in Chrome console `Failed to load resource: the server responded with a status of 405 (Method Not Allowed)`

Here is an example of  running command inside a container `parity --dapps-hosts all --dapps-interface 0.0.0.0 --dapps-port 8002 --dapps-user user --dapps-pass tcOx48dfEYSDfwANplLtH82tWv4CPh --chain /root/chain.json --force-sealing --author 0x245d22d1c5061d08648a162180800959d79c1f8d --unlock 0x245d22d1c5061d08648a162180800959d79c1f8d --password /root/.parity-pass --rpccorsdomain "*" --jsonrpc-hosts=all --jsonrpc-interface all >&1 1>>/var/log/parity.log 2>&1`

In Dockerfile I expose `EXPOSE 8002` and run container `sudo docker run --name parity-master -p 8545:8545 -p 30303:30303 -p 8001:8001 -p 8002:8002 -d igorbarinov/docker-parity-master`

**Comment by tomusdrw** [comment]
It's a separate issue https://github.com/ethcore/parity/issues/2015.

Try `http://localhost:8002/home/`
