### ISSUE TITLE
Account balance do not show on private chains

### ISSUE THREAD

**Issue by catageek** [paritytech/parity-ui#114]
I set up a private chain with two accounts. Geth show the balances but parity does not show them.

I noticed that some calls were made to the (inexistent) registrar to resolve account names, and get an error. I could see that on Morden the registrar solve account names to address and then get the balance.

So I deployed a Registrar on the chain and provided the address in the json file of the chain, but unfortunately parity is ignoring it.

So what should I do to get the UI works on a private chain ?

**Comment by tomusdrw** [comment]
What version of Parity are you running? This repo is deprecated, 1.4 series will feature new UI and if this issue is related to this new UI please file an issue in main Parity repo here:
https://github.com/ethcore/parity

**Comment by catageek** [comment]
I use the parity of repo parity. I open a ticket in the other repo.
