### ISSUE TITLE
Linux: 127.0.0.1:8180 is a blank page

### ISSUE THREAD

**Issue by cemsbr** [paritytech/parity-ui#116]
I'm having this issue in Linux and parity v1.4.5-beta-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.13.0 both in Firefox and Chromium: `Cannot find module "react/lib/EventPluginHub"`

![blank_page](https://cloud.githubusercontent.com/assets/49481/20643107/08db5b72-b407-11e6-9935-5d1a32e9b753.png)

The blank page is like #8, but that issue was related to "mio/hyper/ws bug on windows."

**Comment by arkpar** [comment]
Should be fixed in the latest beta branch and 1.4.5 release

**Comment by tomusdrw** [comment]
@cemsbr Where did you get that version from? Can you check latest release as @arkpar recommended?

**Comment by cemsbr** [comment]
I got it from the Archlinux repo and its version is `Parity/v1.4.5-beta-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.13.0`.

I download the latest deb, extracted it and ran. No issues! The version that works is `Parity/v1.4.5-beta-a028d04-20161126/x86_64-linux-gnu/rustc1.13.0`.
