### ISSUE TITLE
Chrome Signer: Always attempts to call `web3.eth.getBalance` as Async method

### ISSUE THREAD

**Issue by fabioberger** [paritytech/parity-ui#117]
As per the [web3 documentation](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetbalance) the `web3.eth.getBalance` is synchronous if the optional callback is not supplied. 

### Current Behavior

The web3 instance injected into the browser by Parity Signer chrome extension throws:

```
Uncaught Error: Async methods not supported
```

when running:

```
web3.eth.getBalance('0x09d02g4b12c9486305bb4f4fc93487cdfba74583');
```

### Expected behavior

It should run the method synchronously and returns the balance.

**Comment by tomusdrw** [comment]
Synchronous methods are not supported by design, it's a technical limitation of building browser extensions, Metamask doesn't support them as well. A good explanation is given on Metamask faq page: https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client

**Comment by fabioberger** [comment]
@tomusdrw having synchronous methods be not supported makes complete sense. The reason I started to look into synchronous methods is because the web3 instance injected by Parity Signer is complaining that **Async methods are not supported**.

<img width="860" alt="screenshot 2017-05-23 11 23 13" src="https://cloud.githubusercontent.com/assets/2151492/26347616/67247b9e-3faa-11e7-9cf3-0521e05c1cfd.png">

All of our web3 requests are currently async.

**Comment by tomusdrw** [comment]
Oh, sorry. That actually has to be a typo, I will have a look in the code. So it seems that the call you're trying to make is actually synchronous.

**Comment by tomusdrw** [comment]
Fixed here: https://github.com/paritytech/parity-extension/pull/81

**Comment by fabioberger** [comment]
Ah great, thanks!
