### ISSUE TITLE
Parallel solo mining with claymore results in erratic hash rate

### ISSUE THREAD

**Issue by micwebnet** [paritytech/parity-ui#118]
When mining across 5 systems with ethminer, I see a stable hash rate of about 180MH/s. Variance is low.

Doing the same with claymore I see hash rate jump from 20s to 130s. Each respective miner shows a steady MHs rate (these are 7x R9 290s, so about 25MHs). 

Claymore EthMan (Ethereum Miner Manager) shows correct hash rates and the sum of ~180MHs across 5 systems with 7 GPUs. 

Who do I trust? Claymore UI with its expected rates or Parity Status UI?

**Comment by tomusdrw** [comment]
parellel mining is not properly supported in the UI filed a separate issue in Parity repo: https://github.com/paritytech/parity/issues/5807

**Comment by micwebnet** [comment]
Works fine for me with ethminer (stable hash rate displayed), but not with claymore (very erratic). Sounds like you made this work already, just not for all common miners.
