### ISSUE TITLE
Parity Status hash rate shows zero when in stratum mode

### ISSUE THREAD

**Issue by micwebnet** [paritytech/parity-ui#119]
When I enable parity in stratum mode, I can connect the miners with -S option, but hash rate in Parity Status UX shows zero. When in pool farm mode it shows nonzero values, as expected. Miners show expected hash rates when in stratum mode. Which do I trust?

**Comment by tomusdrw** [comment]
Collecting hashrates from stratum is currently not supported in the uI. Filed an issue in Parity repo: https://github.com/paritytech/parity/issues/5807

**Comment by micwebnet** [comment]
Can the UI get smarter, and when Parity is in stratum mode, show N/A instead of 0 H/s, until you figure out how to monitor hash rates in push mode?
