### ISSUE TITLE
Parity Signer Ledger Fails to Sign Message

### ISSUE THREAD

**Issue by fabioberger** [paritytech/parity-ui#120]
Parity Signer Chrome Extension + Ledger Nano S works well when sending transactions to the network but fails when trying to sign a message. 

Steps to reproduce the issue:
- Make sure the Ledger Nano S account is selected in Parity Signer.
- Visit [0x OTC DApp](https://0xproject.com/otc).
- Fill in the 'Generate an order' form and click 'SIGN HASH'.
- Click 'CONFIRM REQUEST' in Parity Signer popover.

Expected: To be prompted by the Ledger to confirm the message signing.
Actual: Nothing happens when clicking 'CONFIRM REQUEST' and the user is never prompted by their Ledger. No errors are visible in the console.

**Comment by tomusdrw** [comment]
The same issue in Parity repo: https://github.com/paritytech/parity/issues/6083. Will close that one, since the repo is outdated anyway.
