### ISSUE TITLE
chromeext: Ensure icon on Chrome app store is hidpi

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity-ui#2]
![image](https://cloud.githubusercontent.com/assets/138296/16356447/038ac55c-3ad8-11e6-8a66-92830da01bea.png)

**Comment by goldylucks** [comment]
Uploaded a new promotional image that will replace this.

Should b displayed in the next hour

**Comment by goldylucks** [comment]
so turns out promotional images may take days and up to weeks to get approved.
we might get our images rejected since our image is mainly gray/white, which they ask to avoid.

if we have a black version svg I could make promotional images out of that

**Comment by goldylucks** [comment]
NOTE:
our logo is not ideal from small resolutions due to the very thin lines

Closed

![image](https://cloud.githubusercontent.com/assets/6963212/16484654/a826bd56-3eba-11e6-9fe4-5b30eeb895a4.png)
