### ISSUE TITLE
tx hash - display propagated and confirmed status

### ISSUE THREAD

**Issue by goldylucks** [paritytech/parity-ui#21]
ATM we display the tx hash immediately upon confirmation of transaction, and clicking on it will bring user to transaction not found pg

**Comment by tomusdrw** [comment]
It still doesn't mean that transaction will be visible there (it depends when blockexplorer will kindly update that page) - IMHO it's good as is.

**Comment by tomusdrw** [comment]
We can also see how other apps are solving this (mist / myetherwallet)

**Comment by goldylucks** [comment]
For me it looks like a bug
I click the link and get "not found" message

Ill think of smthn
