### ISSUE TITLE
Wallet - test not responding for 20sec

### ISSUE THREAD

**Issue by goldylucks** [paritytech/parity-ui#23]
(signer is enabled)

**Comment by goldylucks** [comment]
@tomusdrw 
parity is returning `null, txHash`?
so mist treats it like any other transaction.

if we want to keep the time limit, I think parity should return error object with message like "no response for confirming transaction"

**Comment by tomusdrw** [comment]
Parity is returning `0x0` hash. It would be best to either not return anything until it's confirmed/rejected or just to prepare a new API for devs (but that's for the future).

**Comment by goldylucks** [comment]
the wallet is waiting a response, and is stuck on "send ..."

so some things to consider here:
1. the response for the wallet dapp if user doesn't confirm/reject
2. what to do if user confirms after response to dapp has been sent
