### ISSUE TITLE
Conventions: Chain / Network

### ISSUE THREAD

**Issue by goldylucks** [paritytech/parity-ui#29]
decide on one and apply everywhere

I'd go with network to b consistent with the rpc method

**Comment by tomusdrw** [comment]
It's not necessarily the same thing - you can have many networks with the same chain definitions.

**Comment by goldylucks** [comment]
ATM we use the chain to link accounts/tx to etherscan:

Homestead -> https://etherscan.io/
Mordern -> https://testnet.etherscan.io/

when we make a rpc call to get network, parity responds with morden/homestead
tho in cli we pass `chain=morden`

so which one is it?

**Comment by goldylucks** [comment]
swallowed by #45
