### ISSUE TITLE
chromeext: Helpful message if Parity is not found running

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity-ui#3]
Message in Chrome extension popup should be formatted similarly to Chrome sad-face:

![image](https://cloud.githubusercontent.com/assets/138296/16356448/2419d18c-3ad8-11e6-8531-eeaaf25eff8b.png)

Should read:

To function correctly, this extension needs you to install the Parity Ethereum client. Get it here: http://parity.io/
[smaller]
If you think you have already installed Parity, ensure it is already running.
[/smaller]

**Comment by goldylucks** [comment]
IMO most users with extension would also have parity installed, how about we switch the formatting?

To function correctly, this extension needs you to run the Parity Ethereum client.
[smaller]
If you don't have the Parity  Ethereum client installed, Get it here: http://parity.io/
[/smaller]
