### ISSUE TITLE
chromeext: Installation screen if Parity is not found

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity-ui#4]
If Parity is not running in Chrome extenstion, the message in the extension popup should be an intelligent download page for Parity.

Should be a simple binary installer for the user's platform - standard big green button with platform information given, latest functional release (at this point, that'd be 1.2.0).

Ubuntu -> .deb, Windows -> .msi, Mac -> .dmg

**Comment by goldylucks** [comment]
c comment in #3

**Comment by goldylucks** [comment]
IMO it would b very rare that user would have the extension and not parity,
and not worth the work of checking for each OS and matching the binary

ATM we present a link to release page

can I close this for now?

**Comment by goldylucks** [comment]
closing for now
