### ISSUE TITLE
Tooltip with "New pending transaction" should contain something meaningful

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ui#46]
It should have a link to Signer and description what actually happened (new pending transaction doesn't say anything to someone who have no idea about Trusted Signer)

Also text on the popup is blury, and trash icon is much too big (subtle X would do)

**Comment by goldylucks** [comment]
> new pending transaction doesn't say anything to someone who have no idea about Trusted Signer

In that case we should do something about extension as well, since ATM it says the same thing

**Comment by tomusdrw** [comment]
In extension is clear - you see the transaction, password input and button.
On webpage it says nothing new:
1. You already clicked a button to send transaction
2. No other action that you can take (except for removing the notification) - How come the user should know they need to open `http://127.0.0.1:8180` or install extension and then confirm the transaction there?

**Comment by goldylucks** [comment]
the toast is clickable and opens the signer in a new tab
(at least in #61)

we could also add some icon tho IMO it's overkill

no strong feelings

**Comment by tomusdrw** [comment]
I thought about a link and more descriptive tooltip message.

```
Confirmation Required.
*Open Trusted Signer* to confirm the transaction.
```
