### ISSUE TITLE
TopBar - Simplify storage

### ISSUE THREAD

**Issue by goldylucks** [paritytech/parity-ui#57]
can we replace the entire localstorage/iframe storage with a simple file on disk?

are there any security concerns regarding that?

**Comment by tomusdrw** [comment]
It's just not possible to do it from the browser?

**Comment by goldylucks** [comment]
some people have LS disabled
wouldn't it b much simpler from the server anyway?

simple json file?

**Comment by goldylucks** [comment]
actually, we could even simplify it further and have a parity method to return all information about the accounts:

```
{ 
  hash: '0x...',
  balance: '0x...',
  name: undefined || 'My friendly name'
}
```

so we avoid messing with names, balances, and hashes on the front end.

thoughts?

**Comment by tomusdrw** [comment]
Yes, that was discussed on last retreat, when we considered wallet implementation.

**Comment by goldylucks** [comment]
following the discussion on slack, just the accounts' names would b persisted in parity
should we keep this issue open here, or move it to parity?

**Comment by tomusdrw** [comment]
https://github.com/ethcore/parity/issues/1109
