### ISSUE TITLE
Signer - reject transaction with error.message

### ISSUE THREAD

**Issue by goldylucks** [paritytech/parity-ui#58]
mist expects an `{ message: 'something bad happens' }`

when user rejects transaction, return:
`{ message: 'Rejected by user' }`

on timeout:
`{ message: 'No response by user' }`

**Comment by tomusdrw** [comment]
Already handled in https://github.com/ethcore/parity/pull/1652

**Comment by tomusdrw** [comment]
Already done https://github.com/ethcore/parity/pull/1667
