### ISSUE TITLE
When Chome-extension not present, transactions should result in popup notification

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity-ui#6]
If there is no Chrome extension then a popup notification should be given to the user whenever a new transaction is present. Clicking the notification should open a correctly sized and undecorated window with the transaction confirmation UI in it (i.e. http://127.0.0.1:8180/).

**Comment by goldylucks** [comment]
A simple "New pending transaction" popup?

**Comment by goldylucks** [comment]
@gavofyork 
now that I think about it, sending a transaction triggers a confirmation dialog.

I think it's better ux then displaying a popup and opening signer in new window

**Comment by tomusdrw** [comment]
A confirmation dialog is triggered only when you run without Signer. I think what gav ment is to have:
1. No signer - Confirmaton Dialog
2. Signer + Extension - No Popup
3. Signer + No Extension - Popup
