### ISSUE TITLE
Signer: Transaction confirmation errors are not handled

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ui#65]
Since we have some more detailed error messages: https://github.com/ethcore/parity/pull/1290

We should display something better in Signer:
![screenshot from 2016-07-18 19 06 32](https://cloud.githubusercontent.com/assets/581548/16923477/c5a35452-4d1a-11e6-8733-8bdb362cda43.png)

**Comment by goldylucks** [comment]
Parity logs an error messgae, tho the response to front end is still `false`
![image](https://cloud.githubusercontent.com/assets/6963212/16947012/c47854d2-4dac-11e6-8aa7-a69c0c4ea1be.png)

**Comment by tomusdrw** [comment]
Yeah, I'm fixing it right now: https://github.com/ethcore/parity/issues/1661
