### ISSUE TITLE
Windows: going to 127.0.0.1:8180 results in blank page

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity-ui#8]
![image](https://cloud.githubusercontent.com/assets/138296/16362025/f981e57e-3ba2-11e6-819f-c1f9fc8aaf95.png)

**Comment by goldylucks** [comment]
@tomusdrw I remember u said something about windows issues coming from server
u know if this is the case here?

**Comment by tomusdrw** [comment]
Yes. It was mio/hyper/ws bug on windows.

**Comment by cemsbr** [comment]
I'm having this issue in Linux and parity v1.4.5-beta-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.13.0 both in Firefox and Chromium.

**Comment by cemsbr** [comment]
(Created a new issue)
