### ISSUE TITLE
Extension: npm install in development version doesn't work

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-ui#88]
Dependency structure:

```
 -extension
  |--signer
     |--components
```

Because there is `postinstall` action in `signer` that links components using relative `npm install` in `extension` doesn't work.

Possible solutions:
1. Remove `postinstall` scripts, and introduce additional step for development.
2. `npm link` using package names - will require to run `npm link` in dependency directory prior to development of dependent project
3. ???

Would be perfect if local development (on a project + dependencies) wouldn't require additional steps.

**Comment by jacogr** [comment]
Having just gone though this, as a short-term...
1. Remove the postinstall scripts
2. Developer run additional `web.sh link` command before starting work

At the current time having an extra step (once-off) to go through is better than doing a `web.sh install` and not having it completed and/or having to do it piecemeal per sub-directory.
